export const Paths = {
    About: 'about-us',
    Accessibility: 'accessibility',
    Analytics: 'analytics',
    Admin: 'admin', 
    AdminManufacturer: 'admin/manufacturers', 
    AllCategories: 'all-categories',
    ArticlesDetails:'articles/technology/technology-is-renovating-the-construction-industry-2',
    Articles: 'articles',
    BIM: 'bim',
    CADAndDetails: 'cad-and-details',
    Catalogs: 'catalogs',
    Certifications: 'certifications',
    ChangePassword: 'myaccount/change-password',
    Collections: 'collections',
    CompareProduct: 'compare/windows?project=d8836e9a-651d-4265-bfa0-de8298c75fc5',
    CompareProductV2: 'compare/v2?ids=',
    ConstructionDetail: 'construction-detail',
    ConstructionDetailsFinder: 'construction-details',
    ContactUs: 'contact',
    CostEstimator: 'window-cost-estimator',
    Courses: 'courses',
    Doors: 'doors',
    Divisions: 'divisions',
    Edit: 'edit',
    FinderQuiz: 'window-finder',
    FindManufacturer: 'find-manufacturer',
    ForManufacturer: 'for-manufacturers', 
    Barrierlink: 'https://acelab-public-site-qa-vnhmkx7udq-uk.a.run.app/',
    ForgotPassword: 'forgot-password',
    HowItWorks: 'how-it-works',
    Home: 'home',
    Inspiration: 'inspiration',
    Manufacturer: 'manufacturers',
    MyAccount: 'myaccount',
    Verificationlink: 'join-company?token=da077359-02c1-4d4b-8155-e6cb132d9c24',
    MyCollections: 'mycollections',
    MyProjects: 'my-projects',
    PrivacyPolicy: 'privacy-policy',
    ProductResearch: 'product-research',
    WindowsProductAdvisor:"divisions/windows/product-advisor",
    ProductNewSearch:"divisions/new-search",
    Project: 'project',
    ProjectInfo: 'project-info',
    ProjectSearch: 'my-searches', 
    ToplavelSearch: 'https://acelab-public-site-qa-vnhmkx7udq-uk.a.run.app/divisions/barriers/all?searchId=3b3ad5d3-895f-455f-91da-2c3717b64e12&page=1', // code added on 09-06-23
    Resources: 'resources',
    Results: 'results',
    Settings: 'settings',
    TermsOfUse: 'terms-of-use',
    ThreePartSpecs: 'three-part-specs',
    Tutorials: 'website-tutorials',
    Window: 'window',
    Windows: 'windows',
    Library: 'my-library' ,
    MyConversations: 'my-conversations',
    DefaultArticle: "/technology/technology-is-renovating-the-construction-industry-2",
    DivisionProductDetail :"/windows/75b4e882-d871-42e7-ae4e-84143ee6eed2?projectId=e6f5b1f7-cb9d-4d13-9cf8-2e5be2d9fb37",
    WindowSearchResultPage: "/windows/results?searchId=785657c4-6c51-49ea-ad1b-df48fde90681&page=1",
    productadvisor:'product-advisor'
};